[env]
TERM  = "xterm-256color"

[window]

dimensions = { columns = 180, lines = 150 }
padding.x=20
padding.y=20

decorations= "Buttonless"
opacity = 0.65

blur = true

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 23

[terminal]
osc52 = "CopyPaste"




